### PR TITLE
feat: enable otlp export

### LINKED ISSUE #53: Enable otlp export

### PR DESCRIPTION
**Pull request by Oleksii-Klimov**

### CODE REVIEW

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Deployment status: success

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Deployment status: success

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Deployment status: success

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Deployment status: success

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Deployment status: success

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Deployment status: success

**Review by adubovik — APPROVED** [review]

**Pull request merged**
